eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}  #This tells the microservice where to find the Eureka Server.
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
